Logout File and Implementation
DV1512/backend pull request #25
Opened 2024-10-17 08:07 UTC by kebabohvo

### Changes
Implemented **logout of user**, by clearing their **sessions and tokens**, the user is returned to **homepage** after logging out.
Removed a mod statement in main for the file and implemented it in the correct mod.rs file.
### Files added
Moved the logout.rs file into auth.

2024-10-17 08:28 UTC, retrokiller543 requested changes
Few major notes that needs to be changed before this can be merged, mainly the endpoint is not registred and has not been tested. Also when you are done run `cargo clippy` and try to fix the errors and warnings that pop up

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +pub async fn end_user_session(email: &String) -> Result<()> {
use `&str`type instead of `&String` to follow rust best practices

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +        println!("{}: Deleted the session", email);
use the logger instead of stout

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +        bail!("No such session!")
please log the error

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +pub async fn clear_tokens(email: &String) -> Result<()> {
same here use `&str`

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +    if let Some(mut session) = UserSession::fetch_by_email(email).await {
use `UserSession::delete` and not clear the tokens and update the db, if the session is expired we need to remove the session and not have empty values

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +        bail!("No such tokens");
same as above, use the logger to log errors

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +    clear_tokens(email).await?;
no need in running clear tokens before removing the session, the same work is being done twice

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +    println!("Logged out!");
use logger

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +        context_path: "/src",
context path should be `/oauth` its not the file path but the url path relative to `/api/<version>` so right now it would be `/api/v1/src/logout` in the docs which is not correct

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +        email: &String,
use `&str`

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +        match logout_user(email).await{
use the short hand `?` and we dont need to redirect the user, just return `200 OK` instead

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/mod.rs
> +pub mod logout;
We need to add docs for the auth module and add the docs, i can do this in the next itteration

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +    fn logout_user_endpoint;
endpoint is not registred in the app, how has this been tested and also please create a function like `oauth_service()` at `src/auth/oauth/mod.rs:32` inside the `src/auth/mod.rs` file and register it in the `v1_endpoints()` function in the main file

2024-10-17 08:28 UTC, retrokiller543 commented on src/auth/logout.rs
> +    fn logout_user_endpoint;
maybe rename this to logout, this will follow the style of the rest of the app

2024-10-17 08:50 UTC, retrokiller543 commented on src/auth/logout.rs
> +        email: &String,
this needs to be a web parameter see the [actix-web](https://actix.rs/docs/request) docs

2024-10-17 11:09 UTC, writemorecode commented on src/auth/logout.rs
> +        session.access_token = String::new();
Maybe use `String::clear` here?
```suggestion
        session.access_token.clear();
```

2024-10-17 11:10 UTC, writemorecode commented on src/auth/logout.rs
> +pub async fn logout_user(email: &str) -> Result<()> {
Don't need to borrow a string slice, just pass it as "f(email)" instead of "f(&email)".

2024-10-17 11:13 UTC, retrokiller543 commented on src/auth/logout.rs
> +        session.access_token = String::new();
As i said in my comment this method is not doing anything as we delete the session afterwards, so probably dont need to think about it to much

2024-10-17 11:15 UTC, writemorecode commented on src/auth/logout.rs
> +                Ok(HttpResponse::InternalServerError().json("Failed to logout User"))
We should not be returning JSON here.

2024-10-17 11:33 UTC, writemorecode commented on src/auth/logout.rs
> +    end_user_session(&email).await?;
Here we are fetching a user session from the database with an email twice. Can we instead fetch the session once and then pass the session to these two functions?

2024-10-17 13:46 UTC, retrokiller543 commented on src/auth/logout.rs
> +                Ok(HttpResponse::InternalServerError().json("Failed to logout User"))
We should probably be using the `body()` metod instead to return plain text or just return 200 OK and nothing im the body

2024-10-17 13:49 UTC, retrokiller543 commented on src/auth/logout.rs
> +    end_user_session(&email).await?;
I agree but we are removing the `clear_token` function so there is no need

2024-10-21 09:46 UTC, writemorecode commented on src/auth/session.rs
> -
Please remove this whitespace.

2024-10-21 09:49 UTC, writemorecode commented on src/auth/oauth/logout.rs
> +                println!("Success logging out");
Remove println

2024-10-21 09:50 UTC, retrokiller543 commented on src/auth/session.rs
> -
This is not needed as we will do a big `cargo fmt` in feature auth after this is merged

2024-10-21 09:52 UTC, writemorecode commented on src/auth/oauth/logout.rs
> +            Err(err) => {
Attempting to logout as an user that is not logged in will in this case return a 500 Internal Server error. What should this return? Maybe a 401 Unauthorized, or a 404?

2024-10-21 09:53 UTC, retrokiller543 commented on src/auth/oauth/logout.rs
> +            Err(err) => {
The best option is maybe `400 Bad request`

2024-10-21 11:51 UTC, retrokiller543 approved these changes

2024-10-21 11:52 UTC, writemorecode approved these changes

2024-10-21 11:53 UTC, merged