Feature: username & password user registration
DV1512/backend pull request #31
Opened 2024-10-24 16:36 UTC by writemorecode

This PR adds an API endpoint for user registration with a username and a password. This endpoint makes use of a new function `register_user`. This function combines the existing `create_user` and `create_auth_for_user` functions into a single new function. The reason for this is to allow us to make use of database transactions. Registering a new user requires three database operations, each of which can fail. If this happens while we are not currently inside a transaction, we may enter an inconsistent state in which, for example, a record has been entered into the "user" and/or the "user_auth" table but not the "auth_for" table. A database transaction solves this problem by waiting to write all changes until all operations have succeeded. Unfortunately, the Rust SDK for SurrealDB does not have support for database transactions. Therefore, we cannot make use of the "db.create" methods. Instead, we combine all three queries into one single large query (wrapped inside the `BEGIN` and `END` clauses).
User passwords are hashed by SurrealDB using the Argon2 algorithm.

2024-10-24 17:51 UTC, retrokiller543 requested changes

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/oauth/mod.rs
> -        schemas(TokenRequest, AccessToken, RefreshToken, TokenResponse, TokenType),
why has some schemas been removed?

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/oauth/register.rs
> +        if let Err(err) = register_user(&state.db, data.0).await {
would recommend to either change the return type of `register_user` to `ServerResponseError` or just use the `?` short hand as the error we return does impl `From<anyhow::Error>`. Also we can map a error using the `map_err` method on Result types. This change from anyhow to our own Error type is a in progress change throughout the project

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/oauth/register.rs
> +            (status = 409, description = "User already exists"),
where do we return this error?

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/users/create.rs
> +) -> Result<()>
maybe change return type here as stated in previous comment

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/users/create.rs
> +    const REGISTER_USER_SQL: &str = "
does not calling `query` several times create a transaction? that might look a bit better, else maybe we create a database function we can use that does this

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/users/create.rs
> +pub async fn register_user<T>(
warning and info logs might be a good addition, this is a change that needs to be done in more endpoints

2024-10-24 17:51 UTC, retrokiller543 commented on src/auth/oauth/register.rs
> +        responses: {
Please add the `500` response here

2024-10-25 09:17 UTC, writemorecode commented on src/auth/oauth/mod.rs
> -        schemas(TokenRequest, AccessToken, RefreshToken, TokenResponse, TokenType),
Whoops, fixed now.

2024-10-25 19:47 UTC, retrokiller543 commented on src/auth/users/create.rs
> +        .query(REGISTER_USER_SQL)
The rest of this method can be made inline and also instead of manually mapping the error we should use the shorthand `?` operator to handle the error thrown by the `check()` method

2024-10-27 13:01 UTC, writemorecode commented on src/auth/oauth/register.rs
> +        responses: {
Done.

2024-10-27 13:07 UTC, writemorecode commented on src/auth/users/create.rs
> +    const REGISTER_USER_SQL: &str = "
No, calling ´query´ multiple times does not create a transaction.

2024-10-27 15:01 UTC, writemorecode commented on src/auth/users/create.rs
> +        .query(REGISTER_USER_SQL)
Done.

2024-10-27 15:01 UTC, writemorecode commented
Ok, can we merge this?

2024-10-27 18:03 UTC, retrokiller543 requested changes
One minor thing i missed before, check the schemas we use in this version to see if my statement is correct but i believe it is

2024-10-27 18:03 UTC, retrokiller543 commented on src/auth/users/create.rs
> +            password = crypto::argon2::generate($password)
we set the value of this field based on what is passed to the field, so all we need is the plain text value

2024-10-28 10:35 UTC, writemorecode commented on src/auth/users/create.rs
> +            password = crypto::argon2::generate($password)
Ok, you mean that it should be "password = $password" instead? Maybe I should be using "INSERT" here instead of create. From what I can understand from the table schema, the database should automatically compute the hash for a given plaintext password. But, when I run this query in Surrealist, the plaintext password is inserted. Do I understand this correctly?

2024-10-28 13:05 UTC, retrokiller543 commented on src/auth/users/create.rs
> +            password = crypto::argon2::generate($password)
You should not need to to use insert, i belive we use create for this in a different place in the API.

2024-10-28 13:06 UTC, retrokiller543 commented on src/auth/users/create.rs
> +            password = crypto::argon2::generate($password)
I could have a look at this during the week

2024-11-04 09:42 UTC, merged