Created API endpoint for updating user data
DV1512/backend pull request #44
Opened 2024-11-06 15:48 UTC by writemorecode

Ok, let's try this again.

This PR adds an API endpoint for updating user information. The fields that can be changed are the username, first and last name, and password. The endpoint uses the PUT method. When the username is updated, the URL safe username is updated accordingly. There is Utoipa API documentation for the endpoint, but it is not perfect. There's some problem with the schema for the type representing the request data format for the endpoint.

2024-11-06 17:08 UTC, retrokiller543 requested changes
Some changes that are needed but also some questions

2024-11-06 17:08 UTC, retrokiller543 commented on src/auth/oauth/update.rs
> +        const SQL: &str = "UPDATE $user_id SET
This query can be constructed and run using the `surrealdb-abstractions` library, it has the same security as the standard api but more safe in the way of making quires as there are less possible syntax errors

2024-11-06 17:08 UTC, retrokiller543 commented on src/auth/oauth/update.rs
> +        const SQL: &str = "UPDATE user_auth SET password = $new_password WHERE ->auth_for->user.id CONTAINS $user_id;";
Same thing about queries here

2024-11-06 17:08 UTC, retrokiller543 commented on src/auth/oauth/update.rs
> +fn url_safe_string(s: String) -> String {
Make this `pub(crate)` and move it to a more central location so we can make it the standard for constructing this field throughout the project

2024-11-06 17:14 UTC, writemorecode commented on src/auth/oauth/update.rs
> +fn url_safe_string(s: String) -> String {
Will do.

2024-11-06 17:14 UTC, writemorecode commented on src/auth/oauth/update.rs
> +        const SQL: &str = "UPDATE $user_id SET
Yes, will change.

2024-11-07 09:52 UTC, writemorecode commented on src/auth/oauth/update.rs
> +    #[serde(flatten)]
The reason for this was to allow for changing a user password without having to send along fields for the username, first and last name, etc. But, since the form we are using on the frontend have these values prefilled, we can change this.

2024-11-07 10:30 UTC, retrokiller543 commented on src/auth/oauth/update.rs
> +    #[serde(flatten)]
another solution for this is to not do flatten and let the frontened be explicit that they want to update user profile data instead of the password, or even do an enum so its either or, this could be good since we then can do only one db query at a time in each flow and is also more inline with how its commonly done, having password be its own thing outside of user data

2024-11-18 13:41 UTC, writemorecode commented
Where are we with this?

2024-11-18 15:19 UTC, writemorecode commented on src/auth/oauth/mod.rs
> +pub(crate) fn url_safe_string(s: &str) -> String {
Yes, I'll remove that.

2024-11-20 09:08 UTC, retrokiller543 approved these changes

2024-11-20 09:08 UTC, merged