File upload service
DV1512/backend pull request #48
Opened 2024-11-29 14:30 UTC by writemorecode

This PR implements a simple file storage service.

Operations:

- Upload files (`POST /files`, supports bulk uploads).
- Delete file and metadata (`DELETE /files/{file_id}`)
- Get file metadata (`GET /files/{file_id}`)
- Get all metadata for user (`GET /files`)
- Download file (`GET /files/{file_id}`)

The filesystem path used to store files is configured using the `FILES_UPLOAD_PATH` environment variable in `env.local`. For security reasons, files are not stored on disk under their original filenames. Instead, they are named as the ID field of the record ID of the metadata record in the database.

2024-12-02 15:31 UTC, retrokiller543 requested changes

2024-12-02 15:31 UTC, retrokiller543 commented on schemas/files_for.surql
> +DEFINE FIELD IF NOT EXISTS in ON files_for TYPE record<file> PERMISSIONS FULL;
Update the query to use the built in way to create relation tables https://surrealdb.com/docs/surrealql/statements/define/table

2024-12-02 15:31 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +        let env_upload_path = tosic_utils::prelude::env!("FILES_UPLOAD_PATH");
would maybe not say that this is a required env var, we could fallback to current dir or use the crate `dirs` to fetch the tmp dir and store them there

2024-12-02 15:31 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +pub struct FilesServiceState {
Maybe move state out of the endpoint module

2024-12-02 15:31 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +struct UploadForm {
Move DTO to dto module

2024-12-02 15:31 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +async fn get_file(
consider using the generate_endpoint macro and possibly split the endpoints into several sepperate fiels, one for each endpoint/http method. Moving it to sepparete files is optional but could make finding in the project easier

2024-12-02 15:31 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +async fn token_from_request<T>(
move this to the extractors module where other extraction logic lives

2024-12-02 15:31 UTC, retrokiller543 commented on src/models/file_metadata.rs
> +pub struct FileMetadataMultiple {
consider a tuple struct instead, we dont really need the named field

2024-12-02 15:31 UTC, retrokiller543 commented on src/services/files.rs
> +struct Filename {
consider tuple struct unless this is stricly needed for Serialization or deserialization

2024-12-02 15:31 UTC, retrokiller543 commented on src/services/files.rs
> +    fn new(filename: &str) -> Self {
if its a tuple struct there is no need for a new method we could then construct this by using `Filename(filename)`

2024-12-02 15:31 UTC, retrokiller543 commented on src/services/files.rs
> +pub async fn insert_file_metadata<T>(
split logic into sepperate files, i would prefer if the structure is something like this

```
files
> mod.rs
> insert.rs
> get.rs
> delete.rs
```

and then re-export them in the `mod.rs`

2024-12-02 15:31 UTC, retrokiller543 commented on src/services/files.rs
> +pub async fn get_file_metadata<T>(
split logic into sepperate files, i would prefer if the structure is something like this

```
files
> mod.rs
> insert.rs
> get.rs
> delete.rs
```

and then re-export them in the `mod.rs`

2024-12-02 15:31 UTC, retrokiller543 commented on src/services/files.rs
> +pub async fn get_file_metadata_by_token<T>(
split logic into sepperate files, i would prefer if the structure is something like this

```
files
> mod.rs
> insert.rs
> get.rs
> delete.rs
```

and then re-export them in the `mod.rs`

2024-12-02 15:31 UTC, retrokiller543 commented on src/services/files.rs
> +pub async fn delete_file_metadata<T>(
split logic into sepperate files, i would prefer if the structure is something like this

```
files
> mod.rs
> insert.rs
> get.rs
> delete.rs
```

and then re-export them in the `mod.rs`

2024-12-02 15:31 UTC, retrokiller543 commented on src/state.rs
> +    pub files: FilesServiceState,
One idea i have had is that we could split the state objects into their own `web::Data` items making it simpler to retrieve the desired state that we need from the API state and ignore any state that is not needed.

2024-12-03 16:36 UTC, writemorecode commented on src/services/files.rs
> +struct Filename {
I tried that, doesn't work. The "filename" field name is used for deserialization to build the query.

2024-12-09 10:36 UTC, retrokiller543 requested changes
Most comments was resolved but not all and one was resolved with no fix or comment about why it was not resolved

2024-12-09 10:36 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +pub struct FilesServiceState {
this is still not resolved, please fix before we merge

2024-12-09 10:36 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +        let env_upload_path = tosic_utils::prelude::env!("FILES_UPLOAD_PATH");
this is still not resolved, please fix before we merge

2024-12-09 10:36 UTC, retrokiller543 commented on src/endpoints/api/files/mod.rs
> +async fn get_file(
Why was this resolved? i cant see a reason for it

2024-12-09 14:18 UTC, writemorecode commented on src/endpoints/api/files/mod.rs
> +        let env_upload_path = tosic_utils::prelude::env!("FILES_UPLOAD_PATH");
I've now fixed this.

2024-12-09 14:19 UTC, writemorecode commented on src/endpoints/api/files/mod.rs
> +pub struct FilesServiceState {
I've now fixed this.

2024-12-11 18:28 UTC, retrokiller543 approved these changes

2024-12-11 18:28 UTC, merged