Vector embeddings service
DV1512/backend pull request #51
Opened 2024-12-13 13:52 UTC by writemorecode

This PR adds an service for inserting and searching for vector embeddings in the database. We are using SurrealDB's support for vector datatypes and search in HNSW vector indices. We create two new tables: `mitigation` and `threat`. These tables store data taken from the MITRE ATT&CK database, as well as the vector embeddings of the description fields of these entries. The metadata stored for each embedding is the name, description, and URL of the database entry.

2024-12-13 15:32 UTC, retrokiller543 commented on src/endpoints/api/embeddings/mod.rs
> +struct AddEmbeddingsRequest {
Move to DTO module

2024-12-13 15:32 UTC, retrokiller543 commented on src/endpoints/api/embeddings/mod.rs
> +struct SearchEmbeddingsRequest {
Move to DTO module

2024-12-13 15:32 UTC, retrokiller543 commented on src/endpoints/api/embeddings/mod.rs
> +async fn add_embeddings(
move to its own post file as all other endpoints, remember everything in the endpoints module is to resemble the actual url endpoint exactly or as closely as possible, that means if several http methods have the same endpoint we will store them in submodules with the name of the http method, see the user endpoint and how we have get and delete, the update file in there should in reality be updated to put.rs instead but try to keep this in mind when working in either repo

2024-12-13 15:32 UTC, retrokiller543 commented on src/endpoints/api/embeddings/mod.rs
> +async fn search_embeddings(
same as above

2024-12-13 15:32 UTC, retrokiller543 commented on src/endpoints/api/embeddings/mod.rs
> +    let json_config = JsonConfig::default().limit(usize::MAX);
possibly make this global for the app?

2024-12-13 15:32 UTC, retrokiller543 commented on src/services/embeddings/add/mod.rs
> +use super::EntryType;
what purpose does it serve to have this as a directory module? if non my OCD brain would say to make it into just add.rs

2024-12-13 15:32 UTC, retrokiller543 commented on src/services/embeddings/mod.rs
> +pub struct MITREEntry {
move to models module

2024-12-13 15:32 UTC, retrokiller543 commented on src/services/embeddings/mod.rs
> +#[derive(Serialize, Deserialize)]
move to models module

2024-12-13 15:32 UTC, retrokiller543 commented on src/services/embeddings/mod.rs
> +pub enum EntryType {
move to models module

2024-12-13 15:32 UTC, retrokiller543 commented on src/services/embeddings/mod.rs
> +impl From<EntryType> for String {
instead implement Display to get the to_string method to be implemented, this is more declaritiv and idiomatic

2024-12-14 14:12 UTC, retrokiller543 requested changes

2024-12-14 14:12 UTC, retrokiller543 commented on src/endpoints/api/embeddings/post.rs
> +pub async fn add_embeddings(
Move into seperate files for each endpoint and if possible use generate Endpoint macro or at minimum document code manually with Utopia

2024-12-14 17:26 UTC, writemorecode commented on src/endpoints/api/embeddings/post.rs
> +pub async fn add_embeddings(
Ok sure I'll fix that, but I thought you said that all endpoints that use the same HTTP method (GET, POST, etc) should be placed in the same file? Or was it in the same module?

2024-12-14 18:17 UTC, retrokiller543 commented on src/endpoints/api/embeddings/post.rs
> +pub async fn add_embeddings(
Same module, say we have a endpoint /api/v1/user/posts and a endpoint /api/v1/user both using GET then the file path will be /api/user/get.rs and /api/user/posts.rs making the file path almost the same as the actual endpoint to make it super simple to know which handler is being used for a given request. Api version is being stripped since they can be reused

2024-12-15 09:01 UTC, retrokiller543 approved these changes

2024-12-15 09:02 UTC, merged